version: "3.8"

services:
  backend:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - chroma
    environment:
      - RAILWAY_VOLUME_MOUNT_PATH=/app/data

  frontend:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000

  chroma:
    image: chromadb/chroma
    ports:
      - "8001:8000"
    environment:
      - RAILWAY_VOLUME_MOUNT_PATH=/chroma/chroma
