version: '3.9'

services:
  backend:
    build: ./api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - chroma
    environment:
      - RAILWAY_VOLUME_MOUNT_PATH=/app/data

  frontend:
    build: ./app
    ports:
      - "8501:8501"
    depends_on:
      - backend

  chroma:
    image: chromadb/chroma
    ports:
      - "8001:8000"
    environment:
      - RAILWAY_VOLUME_MOUNT_PATH=/chroma/chroma
