version: '3.9'

services:
  backend:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - chroma

  frontend:
    build: ./app
    ports:
      - "8501:8501"
    depends_on:
      - backend

  chroma:
    image: chromadb/chroma
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  chroma_data:
