[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 300
startupTimeout = "5m"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5 